<?php
/**
 * @file
 * Code for the Carousel feature.
 */

include_once('msingif_carousel.features.inc');



/**
 * Image style: default style + settings
 *****************************************************************************/
/**
 * Implements hook_image_default_styles().
 */
function msingif_carousel_image_default_styles() {
  $styles = array();

  // Exported image style: carousel
  $styles['carousel'] = array(
    'name' => 'carousel',
    'effects' => array(
      1 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => '620',
          'height' => '400',
        ),
        'weight' => '1',
      ),
    ),
  );

  return $styles;
}
