<?php
/**
 * @file
 * Code for the Carousel feature.
 */

include_once('msingif_carousel.features.inc');



/**
 * Implements hook_menu()
 */
function msingif_carousel_menu() {
  $items = array();
  
  $items['admin/config/msingif/carousel'] = array(
    'title'            => 'Carousel',
    'description'      => 'Configure carousel settings.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('msingif_carousel_settings_form'),
    'access arguments' => array('access administration pages'),
    'file'             => 'msingif_carousel.admin.inc',
    'weight'           => 0,
  );
  
  return $items;
}



/**
 * Image style: default style + settings
 *****************************************************************************/
/**
 * Implements hook_image_default_styles().
 */
function msingif_carousel_image_default_styles() {
  $styles = array();

  // Exported image style: carousel
  $styles['carousel'] = array(
    'name' => 'carousel',
    'effects' => array(
      1 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width'  => variable_get('msingif_carousel_image_width', 620),
          'height' => variable_get('msingif_carousel_image_height', 400),
        ),
        'weight' => '1',
      ),
    ),
  );

  return $styles;
}
