<?php
/**
 * @file
 * msingif_page.features.inc
 */

/**
 * Implements hook_node_info().
 */
function msingif_page_node_info() {
  $items = array(
    'page' => array(
      'name' => t('Basic page'),
      'base' => 'node_content',
      'description' => t('Use basic pages for your static content, such as an \'About us\' page.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
